version: '3'
services:
  server:
    build: .
    network_mode: "host"
    ports:
    - "27104:27104/udp"
    - "27132:27132/udp"
    command: run 
    logging:
     options:
      max-size: "5m"
    restart: always
      
   
