version: '3'
services:
  server:
    build: .
    env_file:
       .env 
    network_mode: "host"
    ports:
    - "${GAME_PORT}:${GAME_PORT}/udp"
    - "${QUERY_PORT}:${QUERY_PORT}/udp"
    command: run 
    logging:
     options:
      max-size: "5m"
    restart: always
      
   
